name: thoughts-stack
services:
  db:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
  ltm:
    # image: "thoughts_ltm_service:latest"
    build:
      context: ./../long_term_memory
      dockerfile: Dockerfile
    env_file: .env
    environment: 
      - KAFKA_SOCKET=kafka-broker:9093
      - KAFKA_CLIENT_ID=ltm_consumer
    ports:
      - "3008:3000"
    volumes:
      - ./../volumes:/ltm
    depends_on:
      - db
  ui:
    build:
      context: ./../ui
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3009:3009"
  ltm-consumer:
    build:
      context: ./../long_term_memory
      dockerfile: Dockerfile
    env_file: .env
    command: bundle exec karafka server
    volumes:
      - ./../volumes:/ltm-consumer
    depends_on:
      - "kafka-broker"
      - db
    environment: 
      - KAFKA_SOCKET=kafka-broker:9093
      - KAFKA_CLIENT_ID=ltm_consumer

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-broker:
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - 9092:9092
      - 9093:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka-broker:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_BROKER_ID=1
    volumes:
      - ./../volumes:/Kafka:/bitnami/kafka-broker
    depends_on:
      - zookeeper
