apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: files-shared
  name: files-shared
  namespace: thoughts-keeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
