apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ltm
  name: ltm
spec:
  ports:
    - name: "3008"
      port: 3008
      targetPort: 3000
  selector:
    io.kompose.service: ltm

---
apiVersion: v1
kind: Service
metadata:
  name: ltm-external
spec:
  type: LoadBalancer
  ports:
    - name: "3008"
      port: 3008
      targetPort: 3000
  selector:
    io.kompose.service: ltm