apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: neo4j-claim2
  name: neo4j-claim2
  namespace: thoughts-keeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
