apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: neo4j
  name: neo4j
  namespace: thoughts-keeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/thoughts-stack-default: "true"
        io.kompose.service: neo4j
    spec:
      containers:
        - env:
            - name: NEO4J_AUTH
              value: neo4j/your_password
          image: neo4j:5.26.0
          name: neo4j
          ports:
            - containerPort: 7474
              hostPort: 7474
              protocol: TCP
            - containerPort: 7687
              hostPort: 7687
              protocol: TCP
          volumeMounts:
            - mountPath: /logs
              name: neo4j-claim0
            - mountPath: /config
              name: neo4j-claim1
            - mountPath: /data
              name: neo4j-claim2
            - mountPath: /plugins
              name: neo4j-claim3
      restartPolicy: Always
      volumes:
        - name: neo4j-claim0
          persistentVolumeClaim:
            claimName: neo4j-claim0
        - name: neo4j-claim1
          persistentVolumeClaim:
            claimName: neo4j-claim1
        - name: neo4j-claim2
          persistentVolumeClaim:
            claimName: neo4j-claim2
        - name: neo4j-claim3
          persistentVolumeClaim:
            claimName: neo4j-claim3
