apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ocr
  name: ocr
  namespace: thoughts-keeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ocr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/thoughts-stack-default: "true"
        io.kompose.service: ocr
    spec:
      containers:
        - args:
            - bundle
            - exec
            - karafka
            - server
          env:
            - name: KAFKA_CLIENT_ID
              value: ocr_service
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_HOST
                  name: env
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_PORT
                  name: env
            - name: KAFKA_SOCKET
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_SOCKET
                  name: env
            - name: LTM_STORAGE_PATH
              valueFrom:
                configMapKeyRef:
                  key: LTM_STORAGE_PATH
                  name: env
            - name: SECRET_KEY_BASE
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY_BASE
                  name: env
          image: thoughts-stack-ocr
          name: ocr
          volumeMounts:
            - mountPath: /ltm
              name: files-shared
      restartPolicy: Always
      volumes:
        - name: files-shared
          persistentVolumeClaim:
            claimName: files-shared
