apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: text-analyzer
  name: text-analyzer
  namespace: thoughts-keeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: text-analyzer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/thoughts-stack-default: "true"
        io.kompose.service: text-analyzer
    spec:
      containers:
        - args:
            - /text_analyzer
          env:
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_HOST
                  name: env
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_PORT
                  name: env
            - name: KAFKA_SOCKET
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_SOCKET
                  name: env
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_URI
                  name: env
            - name: NEO4J_DB
              valueFrom:
                configMapKeyRef:
                  key: NEO4J_DB
                  name: env
            - name: NEO4J_HOST
              valueFrom:
                configMapKeyRef:
                  key: NEO4J_HOST
                  name: env
            - name: NEO4J_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: NEO4J_PASSWORD
                  name: env
            - name: NEO4J_PORT
              valueFrom:
                configMapKeyRef:
                  key: NEO4J_PORT
                  name: env
            - name: NEO4J_USER
              valueFrom:
                configMapKeyRef:
                  key: NEO4J_USER
                  name: env
            - name: TEXT_ANALYZER_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: TEXT_ANALYZER_DB_NAME
                  name: env
          image: thoughts-stack-text_analyzer
          name: text-analyzer
      restartPolicy: Always
