apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
    - name: "3009"
      port: 3009
      targetPort: 80
  selector:
    io.kompose.service: ui

---
apiVersion: v1
kind: Service
metadata:
  name: ui-external
spec:
  type: LoadBalancer
  ports:
    - name: "3009"
      port: 3009
      targetPort: 80
  selector:
    io.kompose.service: ui
