apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: web-sockets-server
  name: web-sockets-server
  namespace: thoughts-keeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-sockets-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/thoughts-stack-default: "true"
        io.kompose.service: web-sockets-server
    spec:
      containers:
        - env:
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_HOST
                  name: env
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_PORT
                  name: env
            - name: KAFKA_SOCKET
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_SOCKET
                  name: env
            - name: SECRET_KEY_BASE
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY_BASE
                  name: env
          image: thoughts-stack-web_sockets_server
          name: web-sockets-server
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
      restartPolicy: Always
